//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFG.OPS.NotificationEngineService.Host.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFG.OPS.NotificationEngineService.Host.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;meta http-equiv=Content-Type content=text/html charset=iso-8859-1&gt;&lt;title&gt;EFG-Hermes Brokerage Enterprise&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;table cellspacing=&apos;3&apos; cellpadding=&apos;1&apos; border=&apos;0&apos; align=&apos;center&apos; width=&apos;100%&apos;&gt;&lt;tr&gt;    &lt;td align=&apos;left&apos; bgcolor=&apos;#579840&apos;&gt;&lt;font face=&apos;tahoma&apos; size=&apos;2&apos; style=&apos;color:#ffffff&apos;&gt;&lt;b&gt;&lt;img src=&apos;https://connect.efg-hermes.com/FILE/webvpn/logo.gif&apos;&gt;&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td align=&apos;left&apos; height=&apos;1&apos; bgcolor=&apos;#CCCCCC&apos;&gt;&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td align=&apos;left&apos; height=&apos;1&apos; bgcolor=&apos;#CCCCCC&apos;&gt;&lt;/td&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MessageBody {
            get {
                return ResourceManager.GetString("MessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Engine service Notification.
        /// </summary>
        internal static string MessageSubject {
            get {
                return ResourceManager.GetString("MessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Engine Service went to fault state..
        /// </summary>
        internal static string NotificationEngineFaulted {
            get {
                return ResourceManager.GetString("NotificationEngineFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Engine service started successfully with the follwoing : {0}.
        /// </summary>
        internal static string NotificationEngineStarted {
            get {
                return ResourceManager.GetString("NotificationEngineStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start Notification Engine service due to the follwoing error :{0}.
        /// </summary>
        internal static string NotificationEngineStartError {
            get {
                return ResourceManager.GetString("NotificationEngineStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop Notification Engine service due to the follwoing error :{0}.
        /// </summary>
        internal static string NotificationEngineStopError {
            get {
                return ResourceManager.GetString("NotificationEngineStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Engine service stopped successfully..
        /// </summary>
        internal static string NotificationEngineStopped {
            get {
                return ResourceManager.GetString("NotificationEngineStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Engine service received unknown message : {0}.
        /// </summary>
        internal static string NotificationEngineUnknownMessage {
            get {
                return ResourceManager.GetString("NotificationEngineUnknownMessage", resourceCulture);
            }
        }
    }
}
